# Generated by Django 4.2.21 on 2025-05-27 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='audiobook_file',
            field=models.CharField(blank=True, help_text='오디오북 파일 경로', max_length=500, null=True),
        ),
    ]
