# Generated by Django 4.2.21 on 2025-05-26 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_thread_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding_vector', models.JSONField(blank=True, null=True)),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='books.book')),
                ('related_books', models.ManyToManyField(blank=True, related_name='related_to', to='books.book')),
            ],
        ),
    ]
