# Generated by Django 4.2.21 on 2025-05-26 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_bookembedding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookembedding',
            name='embedding_vector',
        ),
    ]
