# Generated by Django 4.2.21 on 2025-05-22 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, default='profiles/default.png', help_text='프로필 이미지를 업로드하세요. 없을 경우 기본 이미지가 사용됩니다.', null=True, upload_to='profiles/'),
        ),
    ]
