# Generated by Django 4.2.21 on 2025-05-26 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='saved_books',
            field=models.ManyToManyField(blank=True, related_name='saved_by_users', to='books.book'),
        ),
    ]
